### ISSUE TITLE
Why not use KKT principle?

### ISSUE THREAD

**Issue by jjprincess** [nupam/Support-Vector-Regression#3]
Hello, your code has left a deep impression on me. SVR use Lagrange duality  and KKT to get the answer,but your code use gradient decent to train the model. I wondered if there are some thesis to stand for it? Had Cost function and gradient descent function in svr_rain_predictor.cpp  any Mathematical formulas? 
Waiting for your reply,thank you!

**Comment by nupam** [comment]
Oh, sorry for this late response, the cost function is not actually right, there is no explicit hinging there, that is just one line. but it is there for the sake of memoir of how I started out. The mathematical part, it is based on the fact that SVMs have a solution due to its convex nature, i.e, one minima, so "gradient decent can be used to conclusively find the best solution
". Please let me know if I am wrong or you want something updated.
